json.array!(@prd_ms) do |prd_m|
  json.extract! prd_m, :id, :SKU, :SKU_DVLPR, :SKU_SOURCE_PRD, :PRD_NAME, :PRD_NAME, :PRD_NAME_SUBTITLE, :PRD_DVLPR_ORG_NAME, :PRD_CTGRY_CD, :PRD_TYPE, :SP_PRD_TYPE, :SET_PRD_F, :SET_PRD_TYPE, :SALE_F, :RCVNG_PLCNT_PRD_F, :DLVRY_LD_TIME, :DB_PRD_DLVRY_MTHD, :LIC_TYPE, :LIC_FROM, :LIC_TO, :DSTRBTR_DISP_F, :PRD_ST, :ACDMC_LIC_F, :PRD_DLVRY_MTHD, :PRD_DESC, :PRD_NOTE, :PRD_NOTICE, :PRD_OTHER_INFO, :URL_PRD, :URL_INSTALL_GUID, :URL_LIC_AUTH_GUID, :URL_INSTALLER, :URL_PRD_IMAGE, :URL_DL, :MEMO, :SUBSCRIPTION_LIC_TERM, :SUBSCRIPTION_LIC_TERM_UNIT, :MNT_LIC_TERM, :MNT_LIC_TERM_UNIT, :ACCNT_CD_DVLPR, :ACCNT_CD_VNDR, :RGSTR_DT, :RGSTR_USR, :LST_UPD_DT, :LST_UPD_USR
  json.url prd_m_url(prd_m, format: :json)
end
