INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('NFR_MEDIA_ST', '1', 1, 'NFRメディアステータス', 'free', 'フリー');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('NFR_MEDIA_ST', '2', 2, 'NFRメディアステータス', 'rented', '貸出中');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('NFR_MEDIA_ST', '3', 3, 'NFRメディアステータス', 'unknown', '不明');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('NFR_MEDIA_ST', '4', 4, 'NFRメディアステータス', 'disposed', '廃棄');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WEB_PO_PAY_TYPE', '1', 1, 'WEB発注支払タイプ', 'credit card', 'クレジットカード');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WEB_PO_PAY_TYPE', '2', 2, 'WEB発注支払タイプ', 'paypal', 'PayPal');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WEB_PO_PAY_TYPE', '3', 3, 'WEB発注支払タイプ', 'bank transfer', '銀行振込');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CPN_CLS', '1', 1, 'クーポンクラス', 'product price discount', '単価割引');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CPN_CLS', '2', 2, 'クーポンクラス', 'total sales amount  discount', '総額割引');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CPN_DSCNT_TYPE', '1', 1, 'クーポン値引タイプ', 'discount amount', '割引額（￥）');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CPN_DSCNT_TYPE', '2', 2, 'クーポン値引タイプ', 'discount rate', '割引率（％）');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CARD_BRAND', '1', 1, 'クレジットカードブランド', 'visa', 'VISA');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CARD_BRAND', '2', 2, 'クレジットカードブランド', 'master', 'Master');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CARD_BRAND', '3', 3, 'クレジットカードブランド', 'jcb', 'JCB');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CARD_BRAND', '4', 4, 'クレジットカードブランド', 'american express', 'American Express');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CARD_BRAND', '5', 5, 'クレジットカードブランド', 'diners club', 'Diners Club');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CARD_BRAND', '6', 6, 'クレジットカードブランド', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SYS_USR_ST', '0', 1, 'システムユーザ状態', 'deleted', '削除済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SYS_USR_ST', '1', 2, 'システムユーザ状態', 'normal', '通常');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SYS_USR_ST', '2', 3, 'システムユーザ状態', 'temporary unaccessible', '一時使用停止');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SYS_USR_ST', '3', 4, 'システムユーザ状態', 'unaccessible', '使用禁止');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SERIAL_ST', '1', 1, 'シリアルステータス', 'free', '未発効');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SERIAL_ST', '2', 2, 'シリアルステータス', 'reserved', '引当済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SERIAL_ST', '3', 3, 'シリアルステータス', 'issued', '発行済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SERIAL_ST', '9', 4, 'シリアルステータス', 'other status', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SERIAL_RGSTRTN_TYPE', '1', 1, 'シリアル登録タイプ', 'fbj registration', 'FBJ仕入登録');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SERIAL_RGSTRTN_TYPE', '2', 2, 'シリアル登録タイプ', 'customer registoration', '顧客登録');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PBLCTN_ST', '1', 1, 'パブリシティ配信先ステータス', 'ok', '配信可');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PBLCTN_ST', '2', 2, 'パブリシティ配信先ステータス', 'ng', '配信不可');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PBLCTN_ST', '3', 3, 'パブリシティ配信先ステータス', 'address unknown', '宛先不明');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BOOLEAN', '0', 1, 'ブール値', 'false、no', '無、偽、不可');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BOOLEAN', '1', 2, 'ブール値', 'true、yes', '有、真、可');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BOOLEAN', '-', 3, 'ブール値', 'na', '不明、判断無');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('LICENCE_TYPE', '1', 1, 'ライセンス区分', 'license', '使用権');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('LICENCE_TYPE', '2', 2, 'ライセンス区分', 'maitenance', '保守');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('LICENCE_TYPE', '3', 3, 'ライセンス区分', 'license with maitenance', '使用権保守付');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('LICENCE_TYPE', '9', 4, 'ライセンス区分', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('TERM_UNIT', '1', 1, '期間単位', 'year', '年');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('TERM_UNIT', '2', 2, '期間単位', 'month', '月');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BANK_ACCNT_TYPE', '1', 1, '銀行口座種別', 'savings account', '普通');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BANK_ACCNT_TYPE', '2', 2, '銀行口座種別', 'checking account', '当座');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BANK_ACCNT_TYPE', '3', 3, '銀行口座種別', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTHLY_REPORT_TYPE', '1', 1, '月次レポートタイプ', 'domestic vendor', '国内ベンダー');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTHLY_REPORT_TYPE', '2', 2, '月次レポートタイプ', 'oversea vendor', '海外ベンダー');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTHLY_REPORT_TYPE', '3', 3, '月次レポートタイプ', 'nakae', 'ナカエ専用');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTHLY_REPORT_TYPE', '9', 4, '月次レポートタイプ', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTLY_STTLMNT_MTHD', '1', 1, '月次清算方法', 'invoice', '請求支払');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTLY_STTLMNT_MTHD', '2', 2, '月次清算方法', 'bank transfer', '振込');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTLY_STTLMNT_MTHD', '3', 3, '月次清算方法', 'paypal', 'PayPal');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTLY_STTLMNT_MTHD', '4', 4, '月次清算方法', 'card withdrawal', 'カード引落');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTLY_STTLMNT_MTHD', '5', 5, '月次清算方法', 'Web settlment', 'Web清算カード');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('MONTLY_STTLMNT_MTHD', '9', 6, '月次清算方法', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CSTMR_TYPE ', '1', 1, '顧客タイプ', 'company', '法人');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('CSTMR_TYPE ', '2', 2, '顧客タイプ', 'individual', '個人');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('STOCK_PRD_TYPE', '1', 1, '在庫製品タイプ', 'serial', 'シリアル');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('STOCK_PRD_TYPE', '2', 2, '在庫製品タイプ', 'package', 'パッケージ');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('STOCK_PRD_TYPE', '3', 3, '在庫製品タイプ', 'serial equipment', 'シリアル機器');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('STOCK_PRD_TYPE', '4', 4, '在庫製品タイプ', 'nfr media', 'NFRメディア');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('STOCK_PRD_TYPE', '9', 5, '在庫製品タイプ', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_PRD_TYPE', '1', 1, '仕入製品タイプ', 'consignment serial', '委託シリアル');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_PRD_TYPE', '2', 2, '仕入製品タイプ', 'consignment package', '委託パッケージ');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_PRD_TYPE', '3', 3, '仕入製品タイプ', 'serial', '受発注シリアル');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_PRD_TYPE', '4', 4, '仕入製品タイプ', 'package', '受発注パッケージ');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SPPLR_TYPE', '1', 1, '仕入先タイプ', 'maker direct', 'メーカー直仕入');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SPPLR_TYPE', '2', 2, '仕入先タイプ', 'via sales agent', '販売代理店経由');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_ST', '1', 1, '仕入発注ステータス', 'not order yet', '未発注');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_ST', '2', 2, '仕入発注ステータス', 'ordered', '発注済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_ST', '3', 3, '仕入発注ステータス', 'delively received', '納品受領済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_TYPE', '1', 1, '仕入発注タイプ', 'sales order to purchase', '受注後仕入');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_TYPE', '2', 2, '仕入発注タイプ', 'consignment stock', '委託在庫');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_PAY_TYPE', '1', 1, '仕入発注支払タイプ', 'prepayment', '前払');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PO_PAY_TYPE', '2', 2, '仕入発注支払タイプ', 'account payable payment', '買掛');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PURCHASE_MTHD', '1', 1, '仕入方法', 'parchase order', '注文書');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PURCHASE_MTHD', '2', 2, '仕入方法', 'web site', 'WEB発注');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_1', '1', 1, '取引先種別1', 'vendor account', '仕入先');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_1', '2', 2, '取引先種別1', 'sales account', '販売先');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_1', '9', 3, '取引先種別1', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_2', '1', 1, '取引先種別2', 'maker', 'メーカー');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_2', '2', 2, '取引先種別2', 'supplier', '仕入代理店');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_2', '3', 3, '取引先種別2', 'distributor', '流通代理店');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_2', '4', 4, '取引先種別2', 'customer', '顧客');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('ACCNT_TYPE_2', '9', 5, '取引先種別2', 'unknown', '-');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PRD_SET_TYPE', '1', 1, '製品セットタイプ', 'single item', '単品');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PRD_SET_TYPE', '2', 2, '製品セットタイプ', 'maker set product', 'メーカーセット');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PRD_SET_TYPE', '3', 3, '製品セットタイプ', 'fbj set product', 'FBJセット');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PRD_MEDIA_TYPE', '1', 1, '製品媒体タイプ', 'package', 'パッケージ');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('PRD_MEDIA_TYPE', '2', 2, '製品媒体タイプ', 'download', 'ダウンロード');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_TYPE', '1', 1, '請求タイプ', 'normal bill', '通常請求');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_TYPE', '2', 2, '請求タイプ', 'credit voucher', '赤伝請求');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_TO_TYPE', '1', 1, '請求宛先タイプ', 'customer', '顧客');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_TO_TYPE', '2', 2, '請求宛先タイプ', 'distributor', '流通代理店');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_STTLMNT_TYPE', '1', 1, '請求決済タイプ', 'individual settlement ', '個別決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_STTLMNT_TYPE', '2', 2, '請求決済タイプ', 'total bill', '月次決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_STTLMNT_TYPE', '9', 3, '請求決済タイプ', 'unknown', '-');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_CLS', '1', 1, '請求書クラス', 'montly total bill', '合計請求書');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_CLS', '2', 2, '請求書クラス', 'domestice individual invoice', '国内個別請求書');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('BILL_CLS', '3', 3, '請求書クラス', 'overseas individual invoice', '海外個別請求書');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_CHANNEL', '1', 1, '注文チャネル', 'web store', 'ストア注文');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_CHANNEL', '2', 2, '注文チャネル', 'customer', '顧客注文');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_CHANNEL', '3', 3, '注文チャネル', 'distributor', '流通代理店注文');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '1', 1, '注文決済方法', 'creadit card', 'クレジットカード決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '2', 2, '注文決済方法', 'bank transfer', '銀行振込');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '3', 3, '注文決済方法', 'convinience store settlement', 'コンビニ決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '4', 4, '注文決済方法', 'cash on delivery', '代引決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '5', 5, '注文決済方法', 'account recivable', '売掛決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '6', 6, '注文決済方法', 'distributor settlement', '流通代理店決済');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SO_PAY_TYPE', '9', 7, '注文決済方法', 'unknown', '-');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DLVRY_TYPE', '1', 1, '納入タイプ', 'fbj', 'FBJ納入');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DLVRY_TYPE', '2', 2, '納入タイプ', 'distributor', '流通代理店納入');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DLVRY_TYPE', '3', 3, '納入タイプ', 'customer', 'エンドユーザ納入');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DRVLR_LEAD_TERM', '1', 1, '納品リードタイム', '1 biz day', '1営業日');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DRVLR_LEAD_TERM', '2', 2, '納品リードタイム', '2 to 3 biz days', '2〜3営業日');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DRVLR_LEAD_TERM', '3', 3, '納品リードタイム', '4 to 5 biz days', '4〜5営業日');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DRVLR_LEAD_TERM', '4', 4, '納品リードタイム', '7 biz days ', '7営業日');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('DRVLR_LEAD_TERM', '5', 5, '納品リードタイム', 'contact', '連絡');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SALES_ACCNT_TYPE', '1', 1, '販売先区分', 'distrbutor', '流通代理店');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SALES_ACCNT_TYPE', '2', 2, '販売先区分', 'customer', '顧客');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SALES_ACCNT_TYPE', '3', 3, '販売先区分', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SALES_ACCNT_ST', '1', 1, '販売先取引状態', 'ok', '取引可能');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('SALES_ACCNT_ST', '2', 2, '販売先取引状態', 'ng', '取引停止');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('RTRF_CLS', '1', 1, '返品返金クラス', 'product exchange', '製品変更');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('RTRF_CLS', '2', 2, '返品返金クラス', 'cancel', '注文一部キャンセル');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('RTRF_CLS', '3', 3, '返品返金クラス', 'coupon balance ', 'クーポン適用差額');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('RF_MTHD', '1', 1, '返品返金方法', 'bank transfer', '銀行振込');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('RF_MTHD', '2', 2, '返品返金方法', 'credit card', 'クレジットカード');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('RF_MTHD', '9', 3, '返品返金方法', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('INQ_TYPE', '1', 1, '問合せ種別', 'pre sale inquiry', '購入前お問合せ');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('INQ_TYPE', '2', 2, '問合せ種別', 'post sale inquiry', '購入後お問合せ');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('INQ_TYPE', '9', 3, '問合せ種別', 'other', 'その他');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WHLSL_PRICE_TYPE', '0', 1, '流通代理店製品仕切価格タイプ', 'hide', '非表示');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WHLSL_PRICE_TYPE', '1', 2, '流通代理店製品仕切価格タイプ', 'general', '一般');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WHLSL_PRICE_TYPE', '2', 3, '流通代理店製品仕切価格タイプ', 'special ', '特別');
INSERT INTO CODE_MS  (list_name,code,sort_order,list_name_j,annotation,annotation_j)  VALUES ('WHLSL_PRICE_TYPE', '3', 4, '流通代理店製品仕切価格タイプ', 'first time', '初回取引');
