INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ISL', 'アイスランド', 'Iceland', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IRL', 'アイルランド', 'Ireland', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AZE', 'アゼルバイジャン', 'Azerbaijan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AFG', 'アフガニスタン', 'Afghanistan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('USA', 'アメリカ合衆国', 'United States', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VIR', 'アメリカ領ヴァージン諸島', 'Virgin Islands, U.S.', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ASM', 'アメリカ領サモア', 'American Samoa', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ARE', 'アラブ首長国連邦', 'United Arab Emirates', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('DZA', 'アルジェリア', 'Algeria', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ARG', 'アルゼンチン', 'Argentina', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ABW', 'アルバ', 'Aruba', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ALB', 'アルバニア', 'Albania', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ARM', 'アルメニア', 'Armenia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AIA', 'アンギラ', 'Anguilla', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AGO', 'アンゴラ', 'Angola', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ATG', 'アンティグア・バーブーダ', 'Antigua and Barbuda', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AND', 'アンドラ', 'Andorra', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('YEM', 'イエメン', 'Yemen', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GBR', 'イギリス', 'United Kingdom', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IOT', 'イギリス領インド洋地域', 'British Indian Ocean Territory', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VGB', 'イギリス領ヴァージン諸島', 'Virgin Islands, British', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ISR', 'イスラエル', 'Israel', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ITA', 'イタリア', 'Italy', 'ERU');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IRQ', 'イラク', 'Iraq', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IRN', 'イラン・イスラム共和国', 'Iran, Islamic Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IND', 'インド', 'India', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IDN', 'インドネシア', 'Indonesia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('WLF', 'ウォリス・フツナ', 'Wallis and Futuna', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('UGA', 'ウガンダ', 'Uganda', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('UKR', 'ウクライナ', 'Ukraine', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('UZB', 'ウズベキスタン', 'Uzbekistan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('URY', 'ウルグアイ', 'Uruguay', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ECU', 'エクアドル', 'Ecuador', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('EGY', 'エジプト', 'Egypt', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('EST', 'エストニア', 'Estonia', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ETH', 'エチオピア', 'Ethiopia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ERI', 'エリトリア', 'Eritrea', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SLV', 'エルサルバドル', 'El Salvador', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AUS', 'オーストラリア', 'Australia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('AUT', 'オーストリア', 'Austria', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ALA', 'オーランド諸島', 'Åland Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('OMN', 'オマーン', 'Oman', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NLD', 'オランダ', 'Netherlands', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GHA', 'ガーナ', 'Ghana', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CPV', 'カーボベルデ', 'Cape Verde', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GGY', 'ガーンジー', 'Guernsey', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GUY', 'ガイアナ', 'Guyana', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KAZ', 'カザフスタン', 'Kazakhstan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('QAT', 'カタール', 'Qatar', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('UMI', '合衆国領有小離島', 'United States Minor Outlying Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CAN', 'カナダ', 'Canada', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GAB', 'ガボン', 'Gabon', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CMR', 'カメルーン', 'Cameroon', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GMB', 'ガンビア', 'Gambia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KHM', 'カンボジア', 'Cambodia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MNP', '北マリアナ諸島', 'Northern Mariana Islands', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GIN', 'ギニア', 'Guinea', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GNB', 'ギニアビサウ', 'Guinea-Bissau', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CYP', 'キプロス', 'Cyprus', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CUB', 'キューバ', 'Cuba', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CUW', 'キュラソー', 'Curaçao', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GRC', 'ギリシャ', 'Greece', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KIR', 'キリバス', 'Kiribati', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KGZ', 'キルギス', 'Kyrgyzstan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GTM', 'グアテマラ', 'Guatemala', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GLP', 'グアドループ', 'Guadeloupe', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GUM', 'グアム', 'Guam', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KWT', 'クウェート', 'Kuwait', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('COK', 'クック諸島', 'Cook Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GRL', 'グリーンランド', 'Greenland', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CXR', 'クリスマス島', 'Christmas Island', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GEO', 'グルジア', 'Georgia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GRD', 'グレナダ', 'Grenada', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('HRV', 'クロアチア', 'Croatia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CYM', 'ケイマン諸島', 'Cayman Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KEN', 'ケニア', 'Kenya', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CIV', 'コートジボワール', 'Côte d''Ivoire', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CCK', 'ココス（キーリング）諸島', 'Cocos (Keeling) Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CRI', 'コスタリカ', 'Costa Rica', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('COM', 'コモロ', 'Comoros', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('COL', 'コロンビア', 'Colombia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('COG', 'コンゴ共和国', 'Congo', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('COD', 'コンゴ民主共和国', 'Congo, the Democratic Republic of the', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SAU', 'サウジアラビア', 'Saudi Arabia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SGS', 'サウスジョージア・サウスサンドウィッチ諸島', 'South Georgia and the South Sandwich Islands', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('WSM', 'サモア', 'Samoa', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('STP', 'サントメ・プリンシペ', 'Sao Tome and Principe', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BLM', 'サン・バルテルミー', 'Saint Barthélemy', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ZMB', 'ザンビア', 'Zambia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SPM', 'サンピエール島・ミクロン島', 'Saint Pierre and Miquelon', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SMR', 'サンマリノ', 'San Marino', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MAF', 'サン・マルタン（フランス領）', 'Saint Martin (French part)', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SLE', 'シエラレオネ', 'Sierra Leone', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('DJI', 'ジブチ', 'Djibouti', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GIB', 'ジブラルタル', 'Gibraltar', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('JEY', 'ジャージー', 'Jersey', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('JAM', 'ジャマイカ', 'Jamaica', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SYR', 'シリア・アラブ共和国', 'Syrian Arab Republic', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SGP', 'シンガポール', 'Singapore', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SXM', 'シント・マールテン（オランダ領）', 'Sint Maarten (Dutch part)', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ZWE', 'ジンバブエ', 'Zimbabwe', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CHE', 'スイス', 'Switzerland', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SWE', 'スウェーデン', 'Sweden', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SDN', 'スーダン', 'Sudan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SJM', 'スヴァールバル諸島およびヤンマイエン島', 'Svalbard and Jan Mayen', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ESP', 'スペイン', 'Spain', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SUR', 'スリナム', 'Suriname', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LKA', 'スリランカ', 'Sri Lanka', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SVK', 'スロバキア', 'Slovakia', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SVN', 'スロベニア', 'Slovenia', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SWZ', 'スワジランド', 'Swaziland', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SYC', 'セーシェル', 'Seychelles', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GNQ', '赤道ギニア', 'Equatorial Guinea', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SEN', 'セネガル', 'Senegal', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SRB', 'セルビア', 'Serbia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KNA', 'セントクリストファー・ネイビス', 'Saint Kitts and Nevis', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VCT', 'セントビンセントおよびグレナディーン諸島', 'Saint Vincent and the Grenadines', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SHN', 'セントヘレナ・アセンションおよびトリスタンダクーニャ', 'Saint Helena, Ascension and Tristan da Cunha', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LCA', 'セントルシア', 'Saint Lucia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SOM', 'ソマリア', 'Somalia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SLB', 'ソロモン諸島', 'Solomon Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TCA', 'タークス・カイコス諸島', 'Turks and Caicos Islands', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('THA', 'タイ', 'Thailand', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('KOR', '大韓民国', 'Korea, Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TWN', '台湾（台湾省/中華民国）', 'Taiwan, Province of China', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TJK', 'タジキスタン', 'Tajikistan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TZA', 'タンザニア', 'Tanzania, United Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CZE', 'チェコ', 'Czech Republic', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TCD', 'チャド', 'Chad', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CAF', '中央アフリカ共和国', 'Central African Republic', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CHN', '中華人民共和国', 'China', 'CHY');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TUN', 'チュニジア', 'Tunisia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PRK', '朝鮮民主主義人民共和国', 'Korea, Democratic People''s Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('CHL', 'チリ', 'Chile', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TUV', 'ツバル', 'Tuvalu', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('DNK', 'デンマーク', 'Denmark', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('DEU', 'ドイツ', 'Germany', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TGO', 'トーゴ', 'Togo', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TKL', 'トケラウ', 'Tokelau', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('DOM', 'ドミニカ共和国', 'Dominican Republic', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('DMA', 'ドミニカ国', 'Dominica', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TTO', 'トリニダード・トバゴ', 'Trinidad and Tobago', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TKM', 'トルクメニスタン', 'Turkmenistan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TUR', 'トルコ', 'Turkey', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TON', 'トンガ', 'Tonga', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NGA', 'ナイジェリア', 'Nigeria', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NRU', 'ナウル', 'Nauru', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NAM', 'ナミビア', 'Namibia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ATA', '南極', 'Antarctica', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NIU', 'ニウエ', 'Niue', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NIC', 'ニカラグア', 'Nicaragua', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NER', 'ニジェール', 'Niger', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('JPN', '日本', 'Japan', 'JPY');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ESH', '西サハラ', 'Western Sahara', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NCL', 'ニューカレドニア', 'New Caledonia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NZL', 'ニュージーランド', 'New Zealand', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NPL', 'ネパール', 'Nepal', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NFK', 'ノーフォーク島', 'Norfolk Island', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('NOR', 'ノルウェー', 'Norway', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('HMD', 'ハード島とマクドナルド諸島', 'Heard Island and McDonald Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BHR', 'バーレーン', 'Bahrain', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('HTI', 'ハイチ', 'Haiti', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PAK', 'パキスタン', 'Pakistan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VAT', 'バチカン市国', 'Holy See (Vatican City State)', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PAN', 'パナマ', 'Panama', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VUT', 'バヌアツ', 'Vanuatu', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BHS', 'バハマ', 'Bahamas', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PNG', 'パプアニューギニア', 'Papua New Guinea', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BMU', 'バミューダ', 'Bermuda', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PLW', 'パラオ', 'Palau', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PRY', 'パラグアイ', 'Paraguay', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BRB', 'バルバドス', 'Barbados', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PSE', 'パレスチナ', 'Palestinian Territory, Occupied', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('HUN', 'ハンガリー', 'Hungary', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BGD', 'バングラデシュ', 'Bangladesh', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('TLS', '東ティモール', 'Timor-Leste', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PCN', 'ピトケアン', 'Pitcairn', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('FJI', 'フィジー', 'Fiji', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PHL', 'フィリピン', 'Philippines', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('FIN', 'フィンランド', 'Finland', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BTN', 'ブータン', 'Bhutan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BVT', 'ブーベ島', 'Bouvet Island', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PRI', 'プエルトリコ', 'Puerto Rico', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('FRO', 'フェロー諸島', 'Faroe Islands', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('FLK', 'フォークランド（マルビナス）諸島', 'Falkland Islands (Malvinas)', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BRA', 'ブラジル', 'Brazil', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('FRA', 'フランス', 'France', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('GUF', 'フランス領ギアナ', 'French Guiana', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PYF', 'フランス領ポリネシア', 'French Polynesia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ATF', 'フランス領南方・南極地域', 'French Southern Territories', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BGR', 'ブルガリア', 'Bulgaria', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BFA', 'ブルキナファソ', 'Burkina Faso', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BRN', 'ブルネイ・ダルサラーム', 'Brunei Darussalam', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BDI', 'ブルンジ', 'Burundi', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VNM', 'ベトナム', 'Viet Nam', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BEN', 'ベナン', 'Benin', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('VEN', 'ベネズエラ・ボリバル共和国', 'Venezuela, Bolivarian Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BLR', 'ベラルーシ', 'Belarus', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BLZ', 'ベリーズ', 'Belize', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PER', 'ペルー', 'Peru', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BEL', 'ベルギー', 'Belgium', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('POL', 'ポーランド', 'Poland', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BIH', 'ボスニア・ヘルツェゴビナ', 'Bosnia and Herzegovina', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BWA', 'ボツワナ', 'Botswana', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BES', 'ボネール、シント・ユースタティウスおよびサバ', 'Bonaire, Saint Eustatius and Saba', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('BOL', 'ボリビア多民族国', 'Bolivia, Plurinational State of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('PRT', 'ポルトガル', 'Portugal', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('HKG', '香港', 'Hong Kong', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('HND', 'ホンジュラス', 'Honduras', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MHL', 'マーシャル諸島', 'Marshall Islands', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MAC', 'マカオ', 'Macao', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MKD', 'マケドニア旧ユーゴスラビア共和国', 'Macedonia, the former Yugoslav Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MDG', 'マダガスカル', 'Madagascar', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MYT', 'マヨット', 'Mayotte', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MWI', 'マラウイ', 'Malawi', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MLI', 'マリ', 'Mali', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MLT', 'マルタ', 'Malta', 'ERU');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MTQ', 'マルティニーク', 'Martinique', 'ERU');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MYS', 'マレーシア', 'Malaysia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('IMN', 'マン島', 'Isle of Man', 'GBP');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('FSM', 'ミクロネシア連邦', 'Micronesia, Federated States of', 'USD');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ZAF', '南アフリカ', 'South Africa', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('SSD', '南スーダン', 'South Sudan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MMR', 'ミャンマー', 'Myanmar', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MEX', 'メキシコ', 'Mexico', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MUS', 'モーリシャス', 'Mauritius', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MRT', 'モーリタニア', 'Mauritania', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MOZ', 'モザンビーク', 'Mozambique', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MCO', 'モナコ', 'Monaco', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MDV', 'モルディブ', 'Maldives', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MDA', 'モルドバ共和国', 'Moldova, Republic of', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MAR', 'モロッコ', 'Morocco', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MNG', 'モンゴル', 'Mongolia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MNE', 'モンテネグロ', 'Montenegro', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('MSR', 'モントセラト', 'Montserrat', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('JOR', 'ヨルダン', 'Jordan', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LAO', 'ラオス人民民主共和国', 'Lao People''s Democratic Republic', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LVA', 'ラトビア', 'Latvia', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LTU', 'リトアニア', 'Lithuania', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LBY', 'リビア', 'Libya', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LIE', 'リヒテンシュタイン', 'Liechtenstein', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LBR', 'リベリア', 'Liberia', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('ROU', 'ルーマニア', 'Romania', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LUX', 'ルクセンブルク', 'Luxembourg', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('RWA', 'ルワンダ', 'Rwanda', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LSO', 'レソト', 'Lesotho', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('LBN', 'レバノン', 'Lebanon', NULL);
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('REU', 'レユニオン', 'Réunion', 'EUR');
INSERT INTO COUNTRY_MS (country_cd,country_name,country_name_e,currency_cd) VALUES ('RUS', 'ロシア連邦', 'Russian Federation', NULL);